name: cqrs api release demo
run-name: ${{ github.actor }} running cqrs demo
on:
  push
jobs:
  Explore_GHA
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v3
  - run: echo "The job was triggered by ${{ github.event_name }} event"
  - run: echo "This job is running on ${{ runner.os }}"